build:
  tags:
    - docker
  stage: build
  script:
    - git submodule init && git submodule update
    - make distclean
    - make -j

make-test:
  tags:
    - docker
  stage: test
  script:
    - git submodule init && git submodule update
    - make distclean
    - make -j
    - make test -j

node-redis-test:
  tags:
    - shell
  stage: test
  script:
    - git submodule init && git submodule update
    - make distclean
    - make -j
    - make install
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.eqalpha.com/keydb-dev/node-redis.git
    - cd node-redis
    - npm install
    - npm run test

jedis-test:
  tags:
    - docker
  stage: test
  script:
    - git submodule init && git submodule update
    - make distclean
    - make -j
    - make install
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.eqalpha.com/keydb-dev/jedis.git
    - cd jedis
    - mkdir tmp
    - make test