build:
  stage: build
  script:
    - git submodule init && git submodule update
    - make distclean
    - make -j
    - make uninstall
    - make install

make-test:
  stage: test
  script:
    - make test

node-redis-test:
  stage: test
  script:
    - mkdir node-redis-test
    - cd node-redis-test
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.eqalpha.com/keydb-dev/node-redis.git
    - cd node-redis
    - npm install
    - npm run test
    - cd ../..
    - rm -rf node-redis-test